---
slug: softcoverdocker
filename: softcoverdocker
title: How to use the softcover docker image to publish your book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2021
uuid: 0e2b049d-6059-435f-91d0-acb079c1a581
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
