---
slug: softcoverdocker
filename: softcoverdocker
title: Softcover on Docker
subtitle: Run softcover publishing commands from docker containers
description: Learn how to use docker containers to run the softcover command line tool.
author: Areg Sarkissian
copyright: 2021
uuid: 0e2b049d-6059-435f-91d0-acb079c1a581
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
