---
authors:
  - name: "Areg Sarkissian"
    image: /images/testimonial_1.png
    contact_email: "aregsar@hoybay.com"
    contact_twitter: "@aregsar"
    contact_fb: ""
    contact_gh: "@aregsar"
    bio: |
      I'm Areg Sarkisssian, a software developer living in Southern California.
      I have worked on software projects for many companies, including America Online and Disney.
      Find out more about me at my [Blog](https://aregsar.com/about) and [@aregsar](https://twitter.com/aregsar).
