---
authors:
  - name: "The Author"
    image: /images/testimonial_1.png
    contact_email: "info@softcover.io"
    contact_twitter: "@softcover"
    contact_fb: "http://facebook.com/softcover"
    contact_gh: "@softcover"
    bio: |
      Author bio [link](https://www.softcover.io)
