---
authors:
  - name: "Areg Sarkissian"
    image: /images/testimonial_1.png
    contact_email: "aregsar@hoybay.com"
    contact_twitter: "@aregsar"
    contact_fb: ""
    contact_gh: "@aregsar"
    bio: |
      Author bio [Areg Sarkissian](https://aregsar.com/about)
